### ISSUE TITLE
Configuration errors with provided client secrete

### ISSUE THREAD

**Issue by Lsinkololwe** [matt-wigg/next-14-azure-auth#48]
I'm having the below challenge when authenticating.

![image](https://github.com/user-attachments/assets/92b5bc81-13d7-4eb6-a1ec-d054e26953cb)

How can this be resolved

**Comment by matt-wigg** [comment]
@Lsinkololwe, are you sure you are using Microsoft Entra ID as your IDP and that it has been configured as expected in Azure?
https://authjs.dev/getting-started/providers/microsoft-entra-id

**Comment by Lsinkololwe** [comment]
@matt-wigg  The mistake was in the way I configured the app in Microsoft Entra ID admin center. I had earlier configured my app as a SPA under platform configurations; after switching to a Web app I no longer have the error.
