### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by tvone** [matt-wigg/next-14-azure-auth#60]
I have added app roles, how do I get the returned results to have the role information of the logged in user?

**Comment by tvone** [comment]
![image](https://github.com/user-attachments/assets/8fe7e258-a166-466c-9126-3f277ce5a925)
![image](https://github.com/user-attachments/assets/4ce1b3da-4ddd-488e-bf6a-8076092d4f07)

**Comment by matt-wigg** [comment]
Hey @tvone,

You must expand on the `src/app/services/msGraphApi.ts` implementation to retrieve all user app roles.

## Update code

### 1. Update the `authorization.params.scope` to include `AppRoleAssignment.ReadWrite.All`

```typescript
authorization: {
  params: {
    scope: "openid profile email User.Read AppRoleAssignment.ReadWrite.All offline_access",
  },
},
```

### 2. Modify the `getUserDetails` function to fetch app roles

```typescript
"use server";

import { Client } from "@microsoft/microsoft-graph-client";

export async function getUserDetails(accessToken: string) {
  const client = Client.init({
    authProvider: (done) => done(null, accessToken),
  });

  try {
    // Get the user details (/me)
    const userDetails = await client.api("/me").get();

    // Get the user's app roles
    const userAppRoles = await client.api(`/users/${userDetails.id}/appRoleAssignments`).get();

    // Combine the user details and app roles into a single response
    return {
      ...userDetails,
      appRoles: userAppRoles,
    };
  } catch (error) {
    console.error("Error fetching user details or app roles:", error);
    throw error;
  }
}
```

Please refer to the MS Graph REST API docs for more information - https://learn.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http

**Comment by tvone** [comment]
Does microsoft entra id support login from any account not included in the organization? I used another account and logged in and got an error
![image](https://github.com/user-attachments/assets/e2f7b41e-b814-4afb-bace-28c9f9922cc3)
![image](https://github.com/user-attachments/assets/eb58487c-270c-4d64-bef6-679f82200be3)

**Comment by tvone** [comment]
Thank you I fixed it
